Name = input("nama: ")
student_id = input("NIM: ")
Class = input("kelas paralel: ")
ttl = input("tempat/tanggal lahir: ")
address = input("alamat: ")
hobby = input("hobby: ")
phone_number = input("no hp: ")

print(f"nama: {Name}")
print(f"NIM: {student_id}")
print(f"kelas paralel: {Class}")
print(f"tempat/tanggal lahir: {ttl}")
print(f"alamat: {address}")
print(f"hobby: {hobby}")
print(f"no hp: {phone_number}")