nama = input(f"{'Nama':<20}: ")
nim = input(f"{'NIM':<20}: ")
kelas = input(f"{'Kelas Paralel':<20}: ")
ttl = input(f"{'Tempat/Tanggal Lahir':<20}: ")
alamat = input(f"{'Alamat':<20}: ")
hobby = input(f"{'Hobby':<20}: ")
no_hp = input(f"{'No. HP':<20}: ")

print(f"{'Nama':<20}: {nama}")
print(f"{'NIM':<20}: {nim}")
print(f"{'Kelas Paralel':<20}: {kelas}")
print(f"{'Tempat/Tanggal Lahir':<20}: {ttl}")
print(f"{'Alamat':<20}: {alamat}")
print(f"{'Hobby':<20}: {hobby}")
print(f"{'No. HP':<20}: {no_hp}")
